export const API_ENDPOINTS = {
  auth: {
    login: "/auth/login",
    register: "/auth/register",
    verifyOtp: "/auth/verify-otp",
    resendOtp: "/auth/resend-otp",
    logout: "/auth/logout",
  },
  basic: {
    curriculum: "/basic/curriculum",
    lesson: (id: number) => `/basic/lessons/${id}`,
    completeLesson: (id: number) => `/basic/lessons/${id}/complete`,
    unit: (id: number) => `/basic/units/${id}`,
    level: (key: string) => `/basic/levels/${key}`,
    plan: "/basic/plan",
    planPreview: "/basic/plan/preview",
    planReschedule: "/basic/plan/reschedule",
    completeTask: (id: number) => `/basic/plan/tasks/${id}/complete`,
  },
  modules: {
    list: "/modules",
    enroll: (key: string) => `/modules/${key}/enroll`,
  },
  admin: {
    passages: "/admin/passages",
    passage: (id: number) => `/admin/passages/${id}`,
    questions: "/admin/questions",
    question: (id: number) => `/admin/questions/${id}`,
    packages: "/admin/packages",
    package: (id: number) => `/admin/packages/${id}`,
    packageSections: (id: number) => `/admin/packages/${id}/sections`,
    packagePublish: (id: number) => `/admin/packages/${id}/publish`,
  },
  exam: {
    packages: "/ielts/packages",
    package: (id: number) => `/ielts/packages/${id}`,
    start: (packageId: number) => `/ielts/packages/${packageId}/attempts`,
    attempts: "/ielts/attempts",
    attempt: (id: number) => `/ielts/attempts/${id}`,
    answers: (id: number) => `/ielts/attempts/${id}/answers`,
    submit: (id: number) => `/ielts/attempts/${id}/submit`,
    result: (id: number) => `/ielts/attempts/${id}/result`,
  },
} as const;
